uart:
  rx_pin: "${uart_rx_pin}"
  tx_pin: "${uart_tx_pin}"
  baud_rate: 9600

sensor:
  - platform: senseair
    id: senseair_sensor
    co2:
      id: co2
      name: "SenseAir CO2 Value"
    update_interval: 10s
