deep_sleep:
  id: deep_sleep_1
  run_duration: "${run_duration}"
  sleep_duration: "${sleep_duration}"
  #wakeup_pin:
  #  number: "${device_wake_button_pin}"
  #  inverted: True
  #wakeup_pin_mode: KEEP_AWAKE
