substitutions:
  device_name: "switch-lr-main"

esphome:
  name: '${device_name}'
  platform: ESP8266
  board: esp01_1m

wifi:
  # 84:0d:8e:77:59:56
  # use_address: switch_lr_main.local
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

api:

ota:
#  password: !secret otapw

time:
  - platform: homeassistant
    id: homeassistant_time

# Button configuration
binary_sensor:
  - platform: gpio
    name: "${device_name} button_1"
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - light.toggle: light_1

  - platform: gpio
    name: "${device_name} button_2"
    id: button_2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - light.toggle: light_2

  - platform: status
    name: "T2 Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

  - platform: gpio
    pin: GPIO5
    id: relay_2

light:
  - platform: binary
    name: "T2 L1"
    id: light_1
    output: relay_1

  - platform: binary
    name: "T2 L2"
    id: light_2
    output: relay_2

# Status LED for connection
status_led:
  pin:
    number: GPIO13
    inverted: true

sensor:
  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    update_interval: 60s
    accuracy_decimals: 0
  - platform: uptime
    name: '${device_name} Uptime'
    unit_of_measurement: days
    update_interval: 300s
    accuracy_decimals: 1
    filters:
      - multiply: 0.000011574
text_sensor:
  - platform: version
    name: "${device_name} version"
  - platform: wifi_info
    ip_address:
      name: "${device_name} ip"
    ssid:
      name: "${device_name} ssid"
