substitutions:
  device_name: sonoffs20b

esphome:
  name: '${device_name}'
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Only use the following if only one AP with this SSID
  fast_connect: true

api:

logger:

ota:

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  name: "Sonoff S20 Button"
  on_press:
    - switch.toggle: relay
- platform: status
  name: "Sonoff S20 Status"

sensor:
- platform: wifi_signal
  name: '${device_name} WiFi Signal'
  update_interval: 60s
  accuracy_decimals: 0
- platform: uptime
  name: '${device_name} Uptime'
  unit_of_measurement: days
  update_interval: 300s
  accuracy_decimals: 1
  filters:
    - multiply: 0.000011574

switch:
- platform: gpio
  name: "Sonoff S20 Relay"
  pin: GPIO12
  id: relay

output:
- platform: esp8266_pwm
  id: s20_green_led
  pin: GPIO13
  inverted: True

light:
- platform: monochromatic
  name: "Sonoff S20 Green LED"
  output: s20_green_led
