substitutions:
  device_name: "tdisplay-ofc"
  friendly_name: "tdisplay-ofc"
  area: "Office"
  vbat_adc_factor: "1.964"
  vbat_max: "4.2"
  vbat_min: "3.0"
  device_ip: "192.168.1.50"
  sntp_server_0: "192.168.1.1"
  log_level: "DEBUG"

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  area: "${area}"

packages:
  board: !include common/boards/liligo_t-display_v1.1.yaml
  wifi_static: !include common/component/wifi_static.yaml
  mqtt: !include common/component/mqtt.yaml
  sntp: !include common/component/sntp.yaml
  # vbat: !include common/component/vbat_adc.yaml
  sen55: !include common/sensors/sen55.yaml
  senseair: !include common/sensors/senseair_s8.yaml

logger:
  level: "${log_level}"

binary_sensor:
  - id: !extend button_1
    internal: true
    on_click:
      if:
        condition:
          light.is_on: back_light
        then:
          - light.dim_relative:
              id: back_light
              relative_brightness: -20%
        else:
          - light.turn_on: back_light
  - id: !extend button_2
    internal: true
    on_click:
      then:
        - light.toggle: back_light

# Define colors
color:
  - id: white
    hex: FFFFFF
  - id: magenta
    hex: FF00FF
  - id: red
    hex: FF0000
  - id: orange
    hex: FFAA00
  - id: yellow
    hex: FFFF00
  - id: green
    hex: 00FF00
  - id: dark_green
    hex: 00AA00

# Include custom fonts
font:
  - file: "gfonts://Roboto+Condensed"
    id: font_text
    size: 22

display:
  - id: !extend shottimer_display
    lambda: |-
      #define LEADING 24
      #define H_CENTER 120

      int line = 0;

      // See: https://www.airgradient.com/documents/infographics/AQ-Monitor-Cheatsheet.pdf
      // See: https://atmotube.com/atmocube-support/indoor-air-quality-index-iaqi
      std::map<int, esphome::Color> co2_color_thresholds
      {
        {    0, dark_green},
        {  600, green},
        {  800, yellow},
        { 1000, orange},
        { 1500, red},
        { 1800, magenta}
      };

      std::map<int, esphome::Color> nox_color_thresholds
      {
        {   0, dark_green},
        {  50, green},
        {  75, yellow},
        { 100, orange},
        { 300, red},
        { 350, magenta}
      };

      std::map<int, esphome::Color> voc_color_thresholds
      {
        {   0, dark_green},
        {  50, green},
        {  75, yellow},
        { 100, orange},
        { 300, red},
        { 350, magenta}
      };

      std::map<int, esphome::Color> pm_1_0_color_thresholds
      {
        {  0, dark_green},
        { 15, green},
        { 25, yellow},
        { 35, orange},
        { 62, red},
        { 96, magenta}
      };

      std::map<int, esphome::Color> pm_2_5_color_thresholds
      {
        {  0, dark_green},
        { 21, green},
        { 36, yellow},
        { 51, orange},
        { 91, red},
        { 141, magenta}
      };

      std::map<int, esphome::Color> pm_10_0_color_thresholds
      {
        {  0, dark_green},
        { 31, green},
        { 51, yellow},
        { 76, orange},
        { 126, red},
        { 201, magenta}
      };

      float co2_ppm = id(co2).state;
      auto co2_color = co2_color_thresholds.lower_bound(co2_ppm) -> second;

      float nox_index = id(nox).state;
      auto nox_color = nox_color_thresholds.lower_bound(nox_index) -> second;

      float voc_index = id(voc).state;
      auto voc_color = voc_color_thresholds.lower_bound(voc_index) -> second;

      float pm_1_0_mg_m3 = id(pm_1_0).state;
      auto pm_1_0_color = pm_1_0_color_thresholds.lower_bound(pm_1_0_mg_m3) -> second;

      float pm_2_5_mg_m3 = id(pm_2_5).state;
      auto pm_2_5_color = pm_2_5_color_thresholds.lower_bound(pm_2_5_mg_m3) -> second;

      float pm_10_0_mg_m3 = id(pm_10_0).state;
      auto pm_10_0_color = pm_10_0_color_thresholds.lower_bound(pm_10_0_mg_m3) -> second;

      it.printf(0, LEADING * line++, id(font_text), TextAlign::TOP_LEFT, "Tem: %4.1f°C", id(sen5x_temperature).state);
      it.printf(0, LEADING * line++, id(font_text), co2_color, TextAlign::TOP_LEFT, "CO2: %4.0f", co2_ppm);
      it.printf(0, LEADING * line++, id(font_text), nox_color, TextAlign::TOP_LEFT, "NOx: %4.1f", nox_index);
      it.printf(0, LEADING * line++, id(font_text), voc_color, TextAlign::TOP_LEFT, "VOC: %4.1f", voc_index);
      line = 0;
      it.printf(H_CENTER, LEADING * line++, id(font_text), TextAlign::TOP_LEFT, "Hum: %4.1f%%", id(sen5x_humidity).state);
      it.printf(H_CENTER, LEADING * line++, id(font_text), pm_1_0_color, TextAlign::TOP_LEFT, "PM1.0:  %4.1f", pm_1_0_mg_m3);
      it.printf(H_CENTER, LEADING * line++, id(font_text), pm_2_5_color, TextAlign::TOP_LEFT, "PM2.5:  %4.1f", pm_2_5_mg_m3);
      it.printf(H_CENTER, LEADING * line++, id(font_text), TextAlign::TOP_LEFT, "PM4.0:  %4.1f", id(pm_4_0).state);
      it.printf(H_CENTER, LEADING * line++, id(font_text), pm_10_0_color, TextAlign::TOP_LEFT, "PM1.0:  %4.1f", pm_10_0_mg_m3);
      // it.printf(it.get_width()/2, it.get_height()/2, id(font_text), color_text, TextAlign::CENTER, "%.2f", id(battery_voltage).state);
