substitutions:
  # c4:4f:33:56:f9:99
  device_name: "tenergy-56f999"
  friendly_name: "tenergy-ofc"
  area: "Office"
  device_ip: "192.168.1.30"
  status_led_pin: GPIO05
  device_wake_button_pin: GPIO00
  voltage_divider: "1.810"
  temperature_offset: "-0.26"
  humidity_offset: "0.759"
  pressure_offset: "0.126"
  vbat_max: "4.2"
  vbat_min: "3.5"
  sleep_duration: 120s
  run_duration: 200ms
  log_level: DEBUG

packages:
  device_base: !include common/bme280_base.yaml
  wifi_static: !include common/wifi_static.yaml
  mqtt_sleep: !include common/mqtt_sleep.yaml
  deep_sleep: !include common/deep_sleep.yaml
