substitutions:
  device_name: "tminia"
  device_ip: "192.168.1.41"
  status_led_pin: GPIO19
  device_wake_button_pin: GPIO00
  voltage_divider: "1.944"
  vbat_max: "4.2"
  vbat_min: "3.5"
  sleep_duration: 60s
  run_duration: 200ms
  log_level: VERBOSE

packages:
  device_base: !include common/bme280_base.yaml
  wifi_static: !include common/wifi_static.yaml
  mqtt_sleep: !include common/mqtt_sleep.yaml
  deep_sleep: !include common/deep_sleep.yaml
